import { useEffect, useMemo, useState } from "react";
import { AppHeader } from "@/components/AppHeader";
import { Button } from "@/components/ui/button";
import { fetchLogs, streakFromLogs, type DoseLog } from "@/lib/diary";
import { Disclaimer } from "@/components/Disclaimer";
import { FileText, Flame, Loader2, Share2 } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { DoctorReportDialog } from "@/components/DoctorReportDialog";
import { LegalFooter } from "@/components/LegalFooter";

const FEEL_BADGE: Record<string, { emoji: string; bg: string; label: string }> = {
  better: { emoji: "😊", bg: "bg-safe text-safe-foreground", label: "Better" },
  same: { emoji: "😐", bg: "bg-accent text-accent-foreground", label: "Same" },
  worse: { emoji: "🤒", bg: "bg-danger text-danger-foreground", label: "Worse" },
};

function fmtDate(iso: string) {
  const d = new Date(iso);
  return d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

import { REMEDIES } from "@/data/remedies";

function buildReport(logs: DoseLog[], days = 7): string {
  const since = Date.now() - days * 24 * 60 * 60 * 1000;
  const recent = logs.filter((l) => new Date(l.taken_at).getTime() >= since);
  if (recent.length === 0) {
    return `MedP-AI Health Diary — Last ${days} Days\nNo herbal remedies recorded.\n\n— Generated by MedP-AI`;
  }
  const lines = recent.map((l) => {
    const feel = l.feel ? ` — felt ${l.feel}` : "";
    return `• ${fmtDate(l.taken_at)} — ${l.remedy_local_name} (${l.remedy_name}); dose: ${l.dose}${feel}`;
  });

  // Science Snapshot block — unique remedies used in the period
  const usedIds = Array.from(new Set(recent.map((l) => l.remedy_id)));
  const scienceBlocks: string[] = [];
  for (const id of usedIds) {
    const r = REMEDIES.find((x) => x.id === id);
    if (!r?.science) continue;
    const s = r.science;
    scienceBlocks.push(
      [
        `── ${r.name} (${r.localName}) ──`,
        `Active phytochemicals: ${s.phytochemicals.join(", ")}`,
        `Clinical evidence: ${s.evidence.citation} — ${s.evidence.summary}`,
        s.toxicity.ld50 ? `Toxicity (LD50): ${s.toxicity.ld50}` : null,
        `Toxicity notes: ${s.toxicity.notes}`,
        s.cypInteraction ? `Pharmacokinetic flag: ${s.cypInteraction}` : null,
        `Source: ${s.source.label} — ${s.source.url}`,
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  return [
    `MedP-AI Health Diary — Last ${days} Days`,
    `Doses logged: ${recent.length}`,
    "",
    ...lines,
    "",
    ...(scienceBlocks.length
      ? ["═══ SCIENCE SNAPSHOT (for clinician review) ═══", "", ...scienceBlocks, ""]
      : []),
    "Note: These are self-reported herbal remedies. I be AI, I no be Doctor.",
    "— Generated by MedP-AI",
  ].join("\n");
}

const Diary = () => {
  const [logs, setLogs] = useState<DoseLog[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [reportOpen, setReportOpen] = useState(false);

  useEffect(() => {
    let alive = true;
    fetchLogs(30)
      .then((d) => alive && setLogs(d))
      .catch((e) => {
        console.error(e);
        alive && setLogs([]);
      })
      .finally(() => alive && setLoading(false));
    return () => {
      alive = false;
    };
  }, []);

  const streak = useMemo(() => (logs ? streakFromLogs(logs) : 0), [logs]);
  const total = logs?.length ?? 0;

  function copyReport() {
    if (!logs) return;
    const text = buildReport(logs, 7);
    navigator.clipboard.writeText(text).then(
      () => toast({ title: "Report copied 📋", description: "Paste am for any chat or email." }),
      () =>
        toast({
          title: "Couldn't copy",
          description: "Long-press the text below to copy manually.",
        }),
    );
  }

  // (legacy text WhatsApp share replaced by DoctorReportDialog with PDF attach)

  return (
    <div className="min-h-screen bg-background">
      <AppHeader />
      <main className="container max-w-2xl py-6 space-y-6">
        <section className="space-y-2">
          <span className="inline-flex items-center gap-1.5 rounded-full border-2 border-foreground bg-accent px-3 py-1 font-mono-tech text-[10px] font-bold uppercase text-accent-foreground shadow-brutal-sm">
            Health Diary
          </span>
          <h1 className="font-display text-3xl leading-[1.05]">
            Your <span className="text-primary">progress</span>
          </h1>
          <p className="text-sm text-muted-foreground">
            Every dose you tick gets saved here so you fit show Pharmacist later.
          </p>
        </section>

        {/* Streak + total */}
        <section className="grid grid-cols-2 gap-3">
          <div className="rounded-xl border-2 border-foreground bg-primary p-4 text-primary-foreground shadow-brutal">
            <div className="flex items-center gap-1.5">
              <Flame className="h-4 w-4" />
              <p className="font-mono-tech text-[10px] uppercase tracking-wider opacity-90">Streak</p>
            </div>
            <p className="mt-1 font-display text-3xl leading-none">{streak}</p>
            <p className="mt-1 font-display text-xs uppercase">
              {streak === 0 ? "Start today" : streak === 1 ? "1 Day Strong!" : `${streak} Days Strong!`}
            </p>
          </div>
          <div className="rounded-xl border-2 border-foreground bg-card p-4 shadow-brutal">
            <p className="font-mono-tech text-[10px] uppercase tracking-wider text-muted-foreground">
              Total doses
            </p>
            <p className="mt-1 font-display text-3xl leading-none">{total}</p>
            <p className="mt-1 font-display text-xs uppercase text-muted-foreground">
              Last 30 days
            </p>
          </div>
        </section>

        {/* Doctor report — formal PDF */}
        <section className="rounded-xl border-2 border-foreground bg-accent p-4 text-accent-foreground shadow-brutal">
          <p className="font-display text-sm uppercase tracking-wider">
            Generate Report for Doctor / Pharmacist
          </p>
          <p className="mt-1 text-xs">
            Hospital-style PDF with letterhead, dose table & science notes — ready to print or share.
          </p>
          <div className="mt-3 grid grid-cols-2 gap-2">
            <Button
              size="lg"
              className="h-12 border-2 border-foreground bg-primary font-display text-sm uppercase text-primary-foreground shadow-brutal-sm brutal-press hover:bg-primary/90"
              onClick={() => setReportOpen(true)}
              disabled={!logs || logs.length === 0}
            >
              <FileText className="h-4 w-4" /> Generate PDF
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="h-12 border-2 border-foreground bg-background font-display text-sm uppercase text-foreground shadow-brutal-sm brutal-press"
              onClick={copyReport}
              disabled={!logs || logs.length === 0}
            >
              <Share2 className="h-4 w-4" /> Copy text
            </Button>
          </div>
        </section>

        <DoctorReportDialog
          open={reportOpen}
          onOpenChange={setReportOpen}
          logs={logs ?? []}
        />

        {/* Log list */}
        <section className="space-y-3">
          <h2 className="font-display text-lg uppercase">Recent doses</h2>
          {loading && (
            <div className="flex items-center gap-2 rounded-xl border-2 border-dashed border-foreground/30 bg-muted p-6 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading your diary…
            </div>
          )}
          {!loading && logs && logs.length === 0 && (
            <div className="rounded-xl border-2 border-dashed border-foreground/40 bg-muted p-6 text-center text-sm text-muted-foreground">
              No dose logged yet. Pick a remedy and check off the <strong>DRINK</strong> step.
            </div>
          )}
          {!loading && logs && logs.length > 0 && (
            <ul className="space-y-3">
              {logs.map((l) => {
                const fb = l.feel ? FEEL_BADGE[l.feel] : null;
                return (
                  <li
                    key={l.id}
                    className="flex items-center gap-3 rounded-xl border-2 border-foreground bg-card p-3 shadow-brutal-sm"
                  >
                    <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-md border-2 border-foreground bg-background text-2xl">
                      {l.remedy_emoji}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-base">✅</span>
                        <p className="truncate font-display text-base leading-tight">
                          {l.remedy_local_name}
                        </p>
                      </div>
                      <p className="font-mono-tech text-[10px] uppercase text-muted-foreground">
                        {fmtDate(l.taken_at)} · {l.dose}
                      </p>
                    </div>
                    {fb && (
                      <span
                        className={`shrink-0 rounded-full border-2 border-foreground px-2 py-0.5 font-mono-tech text-[10px] font-bold uppercase shadow-brutal-sm ${fb.bg}`}
                      >
                        {fb.emoji} {fb.label}
                      </span>
                    )}
                  </li>
                );
              })}
            </ul>
          )}
        </section>

        <Disclaimer />
      </main>
      <LegalFooter />
    </div>
  );
};

export default Diary;
