import { AppHeader } from "@/components/AppHeader";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      <AppHeader />
      <main className="container max-w-3xl py-8">
        <Link
          to="/"
          className="mb-6 inline-flex items-center gap-1.5 font-mono-tech text-xs uppercase text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back
        </Link>

        <article className="prose prose-slate max-w-none">
          <header className="mb-8 border-b-2 border-foreground pb-6">
            <p className="font-mono-tech text-xs uppercase tracking-wider text-muted-foreground">
              Legal · MedP-AI
            </p>
            <h1 className="mt-2 font-display text-4xl leading-tight">Terms of Service</h1>
            <p className="mt-3 text-sm text-muted-foreground">
              Effective date: <em>To be set on publication</em>
            </p>
          </header>

          <section className="space-y-8 text-sm leading-relaxed text-foreground">
            <div>
              <h2 className="font-display text-2xl">1. Acceptance of Terms</h2>
              <p className="mt-2">
                By creating an account or using MedP-AI ("the App"), you agree to be bound by
                these Terms of Service. If you do not agree, do not use the App.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">2. Eligibility</h2>
              <p className="mt-2">
                You must be at least 18 years old, or have the consent of a parent or guardian, to
                use this App.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">3. Medical Disclaimer</h2>
              <div className="mt-2 rounded-xl border-2 border-danger bg-danger/10 p-4">
                <p className="font-display text-xs uppercase tracking-wider text-danger">
                  Important
                </p>
                <p className="mt-2">
                  MedP-AI provides pharmaceutical and herbal information <strong>for academic
                  and informational purposes only</strong>. It is <strong>not</strong> a
                  substitute for professional medical advice, diagnosis, or treatment. Information
                  generated by AI may be incomplete or incorrect. Always consult a licensed
                  pharmacist, doctor, or qualified healthcare provider before taking any remedy,
                  changing medication, or acting on App content. In an emergency, call your local
                  emergency services immediately. The App makes no warranty that any remedy
                  shown is safe or effective for your condition.
                </p>
              </div>
            </div>

            <div>
              <h2 className="font-display text-2xl">4. User Conduct</h2>
              <p className="mt-2">When using MedP-AI, you agree that you will not:</p>
              <ul className="ml-6 mt-2 list-disc space-y-1">
                <li>Use the App for any unlawful purpose or in violation of applicable laws.</li>
                <li>Submit false, misleading, or harmful information.</li>
                <li>
                  Attempt to reverse-engineer, scrape, or interfere with the App's systems or
                  security.
                </li>
                <li>
                  Use the App to provide medical advice to others or to operate a clinical
                  practice.
                </li>
                <li>
                  Upload content that infringes intellectual property, contains malware, or
                  violates the privacy of others.
                </li>
                <li>Resell, sublicense, or commercially exploit the App without written consent.</li>
              </ul>
            </div>

            <div>
              <h2 className="font-display text-2xl">5. Account Responsibility</h2>
              <p className="mt-2">
                You are responsible for safeguarding your account credentials and for all
                activity that occurs under your account. Notify us immediately of any
                unauthorised use.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">6. Intellectual Property</h2>
              <p className="mt-2">
                The App, including its source code, design, logos, text, graphics, and curated
                remedy database, is the property of MedP-AI and its licensors and is protected by
                copyright, trademark, and other intellectual-property laws. You are granted a
                limited, non-exclusive, non-transferable, revocable licence to use the App for
                personal, non-commercial purposes. You retain ownership of content you submit
                (such as plant photos), but you grant us a worldwide, royalty-free licence to
                process that content for the purpose of providing App functionality.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">7. AI-Generated Content</h2>
              <p className="mt-2">
                The App uses artificial-intelligence models to identify plants, suggest remedies,
                and generate reports. AI output may contain inaccuracies. You are solely
                responsible for verifying any AI-generated information with a qualified
                professional before relying on it.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">8. Third-Party Services</h2>
              <p className="mt-2">
                The App integrates with third-party services (e.g. mapping and pharmacy data). We
                are not responsible for the availability, accuracy, or policies of those
                services.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">9. Termination</h2>
              <p className="mt-2">
                You may delete your account at any time from the Profile page. We may suspend or
                terminate your access if you violate these Terms.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">10. Limitation of Liability</h2>
              <p className="mt-2">
                To the maximum extent permitted by law, MedP-AI and its operators shall not be
                liable for any indirect, incidental, consequential, or punitive damages arising
                from your use of, or inability to use, the App, including (without limitation)
                any health outcomes resulting from acting on App content.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">11. Changes to These Terms</h2>
              <p className="mt-2">
                We may update these Terms from time to time. Material changes will be notified in
                the App. Continued use after changes constitutes acceptance.
              </p>
            </div>

            <div>
              <h2 className="font-display text-2xl">12. Contact</h2>
              <p className="mt-2">
                For questions about these Terms, contact the MedP-AI team via the in-app feedback
                channel.
              </p>
            </div>

            <p className="border-t-2 border-foreground pt-4 text-xs text-muted-foreground">
              See also: <Link to="/privacy-policy" className="underline">Privacy Policy</Link>.
            </p>
          </section>
        </article>
      </main>
    </div>
  );
};

export default TermsOfService;
