// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my MedP-AI profile",
  description: "Return the signed-in user's MedP-AI profile: display name, active conditions, active medications, HMO info, and privacy state.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select(
      "display_name,email,active_conditions,active_medications,hmo_provider,hmo_member_id,privacy_guard,privacy_acknowledged_at"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-recent-vitals.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_vitals_default = defineTool2({
  name: "list_recent_vitals",
  title: "List recent vitals",
  description: "List the signed-in user's most recent vitals (pulse, blood pressure, glucose) ordered by measurement time, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max rows to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("vitals_logs").select(
      "id,pulse_bpm,systolic,diastolic,glucose_mgdl,signal_quality,source,notes,measured_at"
    ).eq("user_id", ctx.getUserId()).order("measured_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vitals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-vital.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_vital_default = defineTool3({
  name: "log_vital",
  title: "Log a vitals reading",
  description: "Record a new vitals reading (pulse, blood pressure, glucose) for the signed-in user. All fields are optional but at least one measurement must be provided.",
  inputSchema: {
    pulse_bpm: z2.number().int().min(20).max(250).optional().describe("Heart rate in beats per minute."),
    systolic: z2.number().int().min(50).max(260).optional().describe("Systolic blood pressure (mmHg)."),
    diastolic: z2.number().int().min(30).max(180).optional().describe("Diastolic blood pressure (mmHg)."),
    glucose_mgdl: z2.number().int().min(20).max(800).optional().describe("Blood glucose (mg/dL)."),
    source: z2.string().max(60).optional().describe("Where the reading came from (e.g. 'manual', 'wearable')."),
    notes: z2.string().max(500).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const hasAny = input.pulse_bpm != null || input.systolic != null || input.diastolic != null || input.glucose_mgdl != null;
    if (!hasAny)
      return {
        content: [{ type: "text", text: "Provide at least one of pulse_bpm, systolic, diastolic, glucose_mgdl." }],
        isError: true
      };
    const { data, error } = await sb3(ctx).from("vitals_logs").insert({
      user_id: ctx.getUserId(),
      pulse_bpm: input.pulse_bpm ?? null,
      systolic: input.systolic ?? null,
      diastolic: input.diastolic ?? null,
      glucose_mgdl: input.glucose_mgdl ?? null,
      source: input.source ?? "mcp",
      notes: input.notes ?? null,
      measured_at: (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged vitals reading ${data.id}` }],
      structuredContent: { vital: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-doses.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_doses_default = defineTool4({
  name: "list_recent_doses",
  title: "List recent herbal doses",
  description: "List the signed-in user's most recent herbal remedy doses from the MedP-AI diary, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("dose_logs").select("id,remedy_name,remedy_local_name,remedy_emoji,dose,feel,taken_at").eq("user_id", ctx.getUserId()).order("taken_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { doses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-safety-score.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_safety_score_default = defineTool5({
  name: "get_safety_score",
  title: "Get my Health Safety Score",
  description: "Return the signed-in user's current MedP-AI Health Safety Score, wellness points, and premium discount percentage.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("health_safety_scores").select("score,wellness_points,premium_discount_pct,context,updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { safety: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lfpwbzyxtasanttxfbwi";
var mcp_default = defineMcp({
  name: "medp-ai-mcp",
  title: "MedP-AI",
  version: "0.1.0",
  instructions: "Personal MedP-AI tools for the signed-in user: read your profile, list and log vitals, list your recent herbal doses, and check your Health Safety Score.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_recent_vitals_default, log_vital_default, list_recent_doses_default, get_safety_score_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
