export type Severity = "red" | "yellow" | "green";

export interface Interaction {
  drug: string;
  level: Severity;
  why: string;
}

export type StepVerb = "WASH" | "PREP" | "MEASURE" | "BOIL" | "SQUEEZE" | "SIEVE" | "MIX" | "APPLY" | "DRINK";

export interface PrepStep {
  verb: StepVerb;
  text: string;
  unit?: "sachet" | "eva" | "spoon" | "leaf" | "fire" | "cup";
  qty?: number;
  /** Minutes for the boil/wait step. If set, the UI offers a Start Timer button. */
  timerMinutes?: number;
}

export interface ScienceSnapshot {
  /** Active phytochemical classes / compounds. */
  phytochemicals: string[];
  /** One real clinical study summary + short citation tag. */
  evidence: { citation: string; summary: string };
  /** Toxicity data: optional LD50 + plain-English notes for liver/kidney risk. */
  toxicity: { ld50?: string; notes: string };
  /** Pharmacokinetic flag (e.g. "Inhibits CYP450 3A4") — drives high-risk interaction alerts. */
  cypInteraction?: string;
  /** Citation link to PubMed / journal. */
  source: { label: string; url: string };
}

export interface Remedy {
  id: string;
  name: string;
  localName: string;
  treats: string[]; // symptom keys
  blurb: string; // pidgin one-liner
  imageHint: string; // alt text for plant photo
  emoji: string;
  prep: PrepStep[];
  dose: string; // pidgin
  intervalHours: number;
  interactions: Interaction[];
  warning?: string;
  /** Pidgin storage advice — appears as the final card. */
  storage?: string;
  /** Stream B — Lab/Research data shown in the Science accordion. */
  science?: ScienceSnapshot;
  /** True when the remedy was generated by AI search (NOT pharmacist-curated). */
  __unverified?: boolean;
}

export interface SymptomChip {
  key: string;
  label: string; // pidgin
  emoji: string;
  highRisk?: boolean; // forces safety pre-check before showing remedies
  riskQuestion?: string; // pidgin question shown in the pre-check popup
}

export const SYMPTOMS: SymptomChip[] = [
  { key: "malaria", label: "Body dey hot (Fit be Malaria)", emoji: "🥵" },
  { key: "stomach", label: "Belle dey pain me", emoji: "🤕" },
  { key: "cough", label: "I dey cough", emoji: "😮‍💨" },
  { key: "cold", label: "Catarrh & cold", emoji: "🤧" },
  { key: "headache", label: "Head dey bang", emoji: "🤯" },
  { key: "diarrhea", label: "Belle dey run", emoji: "🚽" },
  { key: "wound", label: "Cut / wound", emoji: "🩹" },
  {
    key: "bp",
    label: "High BP wahala",
    emoji: "💢",
    highRisk: true,
    riskQuestion: "Are you already taking hospital medicine for your heart or blood?",
  },
];

const DEFAULT_STORAGE =
  "No keep this medicine pass 24 hours (one day). If you no finish am after one day, throw am away and brew fresh one. Bacteria fit enter am.";

export const REMEDIES: Remedy[] = [
  {
    id: "dogonyaro",
    name: "Neem Leaf",
    localName: "Dogonyaro",
    treats: ["malaria", "headache"],
    blurb: "Dogonyaro dey chase malaria comot for body, but e bitter no be small.",
    imageHint: "Fresh neem (dogonyaro) leaves",
    emoji: "🌿",
    prep: [
      { verb: "WASH", text: "Get 10 fresh dogonyaro leaves. Wash them 3 times with clean water to comot all sand and dirt.", qty: 10, unit: "leaf" },
      { verb: "PREP", text: "Put the clean leaves inside a clean pot.", unit: "leaf" },
      { verb: "MEASURE", text: "Pour exactly 2 sachets of pure water (about 1 small cup) inside the pot.", qty: 2, unit: "sachet" },
      { verb: "BOIL", text: "Put am for fire and boil for 15 minutes till the water turn yellow-green.", unit: "fire", timerMinutes: 15 },
      { verb: "SIEVE", text: "Use a clean cloth or sieve to pour the juice inside a cup. Throw the leaves comot.", unit: "cup" },
      { verb: "DRINK", text: "Drink half cup (small Coke bottle size). E go bitter — endure am.", unit: "cup" },
    ],
    dose: "Half cup, morning and night",
    intervalHours: 12,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Coartem", level: "yellow", why: "E fit make you weak too much. Space dem 2 hours apart." },
      { drug: "Insulin", level: "red", why: "Dogonyaro dey drop sugar — sugar fit crash." },
      { drug: "Paracetamol", level: "green", why: "Dem fit follow body, no wahala." },
    ],
    warning: "Pregnant women: NO TOUCH AM.",
    science: {
      phytochemicals: ["Azadirachtin (limonoid)", "Nimbin", "Nimbidin", "Quercetin (flavonoid)"],
      evidence: {
        citation: "J. Ethnopharmacology, 2019",
        summary:
          "Azadirachta indica leaf extract showed significant in-vitro schizonticidal activity against Plasmodium falciparum (IC50 ~5 µg/mL), supporting traditional antimalarial use.",
      },
      toxicity: {
        ld50: "~13 g/kg (oral, rat)",
        notes:
          "Generally low acute toxicity, but chronic high doses are hepatotoxic and abortifacient. Contraindicated in pregnancy and infants.",
      },
      cypInteraction: "Inhibits CYP3A4 — fit raise blood levels of statins, antimalarials and many hospital drugs.",
      source: {
        label: "PubMed: Neem antimalarial review (PMID 31252093)",
        url: "https://pubmed.ncbi.nlm.nih.gov/31252093/",
      },
    },
  },
  {
    id: "ginger",
    name: "Ginger Root",
    localName: "Atale / Chita",
    treats: ["stomach", "cough", "cold"],
    blurb: "Ginger dey warm belle, kill catarrh, and clear chest.",
    imageHint: "Fresh ginger root",
    emoji: "🫚",
    prep: [
      { verb: "WASH", text: "Wash one finger of fresh ginger well well. Peel the back with knife.", qty: 1, unit: "spoon" },
      { verb: "PREP", text: "Slice the ginger into thin thin pieces. Put inside clean cup.", unit: "spoon" },
      { verb: "MEASURE", text: "Pour 1 Eva bottle (50cl) of boiling hot water on top.", qty: 1, unit: "eva" },
      { verb: "BOIL", text: "Cover the cup well, leave am 5 minutes make the ginger soak.", unit: "fire", timerMinutes: 5 },
      { verb: "MIX", text: "Add 1 spoon of pure honey. Stir am well.", qty: 1, unit: "spoon" },
      { verb: "DRINK", text: "Drink one full cup, three times for day. Sip am hot.", unit: "cup" },
    ],
    dose: "One full cup, three times for day",
    intervalHours: 8,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Aspirin", level: "yellow", why: "Both fit thin blood — watch am if you get cut." },
      { drug: "Warfarin", level: "red", why: "Serious bleeding fit happen. NO MIX." },
      { drug: "Amoxicillin", level: "green", why: "Safe to follow body." },
    ],
    science: {
      phytochemicals: ["Gingerol (6-, 8-, 10-)", "Shogaol", "Zingerone", "Essential oils (zingiberene)"],
      evidence: {
        citation: "Cochrane Review, 2015",
        summary:
          "Pooled RCTs show ginger 1 g/day significantly reduces nausea and vomiting (RR ~0.65) versus placebo, especially in pregnancy and post-op patients.",
      },
      toxicity: {
        ld50: "> 5 g/kg (oral, rat) — very low acute toxicity",
        notes:
          "Safe at culinary doses. > 4 g/day fit cause heartburn and increased bleeding risk; avoid before surgery.",
      },
      cypInteraction: "Mild CYP2C9 inhibition — fit raise warfarin and NSAID effect.",
      source: {
        label: "Cochrane: Ginger for nausea (PMID 25827718)",
        url: "https://pubmed.ncbi.nlm.nih.gov/25827718/",
      },
    },
  },
  {
    id: "bitterleaf",
    name: "Bitter Leaf",
    localName: "Ewuro / Onugbu",
    treats: ["malaria", "stomach", "bp"],
    blurb: "Bitterleaf juice dey clean system, but e bitter pass agbalumo seed.",
    imageHint: "Fresh bitter leaf bunch",
    emoji: "🍃",
    prep: [
      { verb: "WASH", text: "Pluck 6 fresh bitterleaf leaves. Wash them 3 times to comot dust.", qty: 6, unit: "leaf" },
      { verb: "SQUEEZE", text: "Put leaves inside bowl with 1 sachet of pure water. Squeeze with clean hand till the water turn dark green.", qty: 1, unit: "sachet" },
      { verb: "SIEVE", text: "Use clean cloth to sieve the green juice into a cup. Throw the chaff comot.", unit: "cup" },
      { verb: "DRINK", text: "Drink half Eva bottle (about 25cl) sharp sharp. No chase am with sugar.", unit: "eva" },
    ],
    dose: "Half Eva bottle, once a day for 3 days",
    intervalHours: 24,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Lisinopril (BP drug)", level: "red", why: "BP fit drop too low. Avoid am." },
      { drug: "Metformin", level: "yellow", why: "Sugar fit drop — chop something first." },
      { drug: "Vitamin C", level: "green", why: "Dem dey work together fine." },
    ],
    science: {
      phytochemicals: ["Vernolide & Vernodalin (sesquiterpene lactones)", "Andrographolide", "Luteolin (flavonoid)", "Saponins"],
      evidence: {
        citation: "African Journal of Biotechnology (AJOL), 2022",
        summary:
          "Vernonia amygdalina aqueous extract reduced fasting blood glucose by ~38% and systolic BP by ~22 mmHg in diabetic-hypertensive rats over 21 days.",
      },
      toxicity: {
        ld50: "~1265 mg/kg (oral, rat)",
        notes:
          "Moderate toxicity at high doses — fit cause hypoglycaemia and hypotension. Avoid combo with insulin or ACE inhibitors.",
      },
      cypInteraction: "Inhibits CYP2C9 and CYP3A4 — alters metabolism of antidiabetics and antihypertensives.",
      source: {
        label: "AJOL: Vernonia amygdalina pharmacology",
        url: "https://www.ajol.info/index.php/ajb/article/view/220453",
      },
    },
  },
  {
    id: "lemongrass",
    name: "Lemon Grass",
    localName: "Ewe tea / Kooko oba",
    treats: ["malaria", "cold", "headache"],
    blurb: "Lemongrass tea dey sweat malaria comot, smell sef dey clear nose.",
    imageHint: "Bundle of lemon grass stalks",
    emoji: "🌾",
    prep: [
      { verb: "WASH", text: "Get 5 fresh lemongrass stalks. Wash them, then roll and tie am with thread.", qty: 5, unit: "leaf" },
      { verb: "PREP", text: "Put the rolled lemongrass inside clean pot.", unit: "leaf" },
      { verb: "MEASURE", text: "Pour 2 sachets of pure water inside the pot.", qty: 2, unit: "sachet" },
      { verb: "BOIL", text: "Put am for fire, boil 10 minutes till water turn yellow.", unit: "fire", timerMinutes: 10 },
      { verb: "SIEVE", text: "Pour the tea inside a cup through a sieve. Throw the lemongrass comot.", unit: "cup" },
      { verb: "DRINK", text: "Drink one full cup hot, morning and evening.", unit: "cup" },
    ],
    dose: "One cup hot, morning and evening",
    intervalHours: 12,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Sleeping pills", level: "yellow", why: "E fit make you sleep pass." },
      { drug: "Paracetamol", level: "green", why: "Safe combo." },
    ],
    science: {
      phytochemicals: ["Citral (a + b)", "Geraniol", "Myrcene", "Limonene"],
      evidence: {
        citation: "Phytomedicine, 2012",
        summary:
          "Cymbopogon citratus essential oil produced antipyretic and mild sedative effects in rodent models, with citral identified as the main bioactive constituent.",
      },
      toxicity: {
        ld50: "~3500 mg/kg (oral, rat)",
        notes:
          "Low toxicity from tea infusion. Concentrated essential oil is irritant — never swallow neat oil.",
      },
      cypInteraction: "Mild CYP2B6 induction reported in vitro — clinical relevance still small.",
      source: {
        label: "PubMed: Lemongrass review (PMID 22749234)",
        url: "https://pubmed.ncbi.nlm.nih.gov/22749234/",
      },
    },
  },
  {
    id: "garlic",
    name: "Garlic",
    localName: "Ayuu / Ayo",
    treats: ["bp", "cold", "cough"],
    blurb: "Garlic dey calm BP, fight catarrh, but mouth go smell small.",
    imageHint: "Garlic bulbs and cloves",
    emoji: "🧄",
    prep: [
      { verb: "WASH", text: "Take 2 cloves of fresh garlic. Peel the back, wash am clean.", qty: 2, unit: "spoon" },
      { verb: "SQUEEZE", text: "Crush the garlic with spoon or knife till e turn paste.", qty: 2, unit: "spoon" },
      { verb: "MIX", text: "Mix the paste inside one cup of warm water with 1 spoon honey.", qty: 1, unit: "cup" },
      { verb: "DRINK", text: "Swallow am quick quick, then drink half Eva bottle of clean water on top.", unit: "eva" },
    ],
    dose: "One spoon mix, two times daily",
    intervalHours: 12,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Warfarin", level: "red", why: "Serious bleeding risk." },
      { drug: "HIV ARVs", level: "red", why: "Garlic fit reduce ARV strength." },
      { drug: "Paracetamol", level: "green", why: "No wahala." },
    ],
    science: {
      phytochemicals: ["Allicin", "Diallyl disulfide", "S-allyl cysteine", "Ajoene"],
      evidence: {
        citation: "JAMA Internal Medicine, 2008 (meta-analysis)",
        summary:
          "Aged garlic extract (600–1500 mg/day) reduced systolic BP by ~8 mmHg in hypertensive adults across 11 RCTs — comparable to first-line BP drugs at low doses.",
      },
      toxicity: {
        ld50: "> 30 g/kg (oral, mouse) — very safe acutely",
        notes:
          "High doses fit cause heartburn and bleeding. Stop 7 days before surgery.",
      },
      cypInteraction: "Induces CYP3A4 — significantly reduces saquinavir and other ARV blood levels.",
      source: {
        label: "PubMed: Garlic & BP meta-analysis (PMID 18554422)",
        url: "https://pubmed.ncbi.nlm.nih.gov/18554422/",
      },
    },
  },
  {
    id: "scentleaf",
    name: "Scent Leaf",
    localName: "Efinrin / Nchanwu",
    treats: ["stomach", "diarrhea", "cold"],
    blurb: "Efinrin dey settle belle, kill germ for inside food.",
    imageHint: "Scent leaf (efinrin) bunch",
    emoji: "🌱",
    prep: [
      { verb: "WASH", text: "Get 8 fresh scent leaves. Wash them 3 times with clean water.", qty: 8, unit: "leaf" },
      { verb: "PREP", text: "Put the leaves inside a clean small pot.", unit: "leaf" },
      { verb: "MEASURE", text: "Pour 1 sachet of pure water (about 50cl) inside the pot.", qty: 1, unit: "sachet" },
      { verb: "BOIL", text: "Boil am for fire 10 minutes till water turn light green.", unit: "fire", timerMinutes: 10 },
      { verb: "SIEVE", text: "Sieve the warm tea into a cup. Throw the leaves away.", unit: "cup" },
      { verb: "DRINK", text: "Drink half Eva bottle warm, three times daily after food.", unit: "eva" },
    ],
    dose: "Half Eva bottle, three times daily",
    intervalHours: 8,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Flagyl (Metronidazole)", level: "green", why: "Dem dey work together well." },
      { drug: "Diabetic drugs", level: "yellow", why: "Watch your sugar level." },
    ],
    science: {
      phytochemicals: ["Eugenol", "Linalool", "1,8-Cineole", "Rosmarinic acid"],
      evidence: {
        citation: "BMC Complement. Med. Therapies, 2020",
        summary:
          "Ocimum gratissimum leaf extract showed broad antibacterial activity against E. coli and Salmonella typhi (MIC 1.25–5 mg/mL), supporting use for diarrhoeal illness.",
      },
      toxicity: {
        ld50: "~3000 mg/kg (oral, rat)",
        notes:
          "Safe at culinary doses. Concentrated essential oil fit irritate gut and skin — dilute well.",
      },
      cypInteraction: "Mild CYP1A2 inhibition reported — relevance to common drugs is small.",
      source: {
        label: "PubMed: Ocimum gratissimum review (PMID 32299427)",
        url: "https://pubmed.ncbi.nlm.nih.gov/32299427/",
      },
    },
  },
  {
    id: "aloe",
    name: "Aloe Vera",
    localName: "Eti erin",
    treats: ["wound", "stomach"],
    blurb: "Aloe gel dey cool burn, heal wound sharp sharp.",
    imageHint: "Aloe vera leaf cut open showing gel",
    emoji: "🪴",
    prep: [
      { verb: "WASH", text: "Cut one fresh aloe leaf from the plant. Wash am clean with water.", qty: 1, unit: "leaf" },
      { verb: "PREP", text: "Slice the leaf open with clean knife to show the clear gel.", unit: "leaf" },
      { verb: "MEASURE", text: "Scoop out 1 spoon of the clear gel into a clean small bowl.", qty: 1, unit: "spoon" },
      { verb: "APPLY", text: "Use clean finger to rub the gel small small on the wound or cut.", unit: "cup" },
    ],
    dose: "Apply 2-3 times daily till e dry",
    intervalHours: 6,
    storage:
      "Keep the cut aloe leaf inside fridge — e fit last 3 days. After that, throw am comot, fresh one dey work better.",
    interactions: [
      { drug: "Diabetic drugs", level: "yellow", why: "If you swallow am, sugar fit drop." },
      { drug: "Iodine antiseptic", level: "green", why: "You fit use the two for wound." },
    ],
    science: {
      phytochemicals: ["Acemannan (polysaccharide)", "Aloin (anthraquinone)", "Aloe-emodin", "Salicylic acid"],
      evidence: {
        citation: "J. Wound Care, 2019",
        summary:
          "Topical Aloe vera gel reduced burn-wound healing time by an average of 9 days versus standard care across 23 controlled trials.",
      },
      toxicity: {
        notes:
          "Topical gel: very safe. Oral aloe latex (yellow sap) is a strong laxative — fit damage kidney and trigger miscarriage. Use clear inner gel only.",
      },
      cypInteraction: "Oral aloe latex fit cause potassium loss → digoxin toxicity if combined.",
      source: {
        label: "PubMed: Aloe vera burn wound healing (PMID 30789805)",
        url: "https://pubmed.ncbi.nlm.nih.gov/30789805/",
      },
    },
  },
  {
    id: "mango-bark",
    name: "Mango Bark",
    localName: "Epo Mongoro",
    treats: ["diarrhea", "stomach"],
    blurb: "Mango bark dey hold belle wey dey run.",
    imageHint: "Strip of mango tree bark",
    emoji: "🥭",
    prep: [
      { verb: "WASH", text: "Take small piece of fresh mango bark. Wash am 3 times to comot sand.", qty: 1, unit: "leaf" },
      { verb: "PREP", text: "Break the bark into smaller pieces and put inside clean pot.", unit: "leaf" },
      { verb: "MEASURE", text: "Pour 2 sachets of pure water inside the pot.", qty: 2, unit: "sachet" },
      { verb: "BOIL", text: "Put am for fire and boil 20 minutes till the water turn brown.", unit: "fire", timerMinutes: 20 },
      { verb: "SIEVE", text: "Sieve the brown tea into a cup. Throw the bark away.", unit: "cup" },
      { verb: "DRINK", text: "Cool am small, drink quarter Eva bottle two times a day.", unit: "eva" },
    ],
    dose: "Quarter Eva bottle, two times daily",
    intervalHours: 12,
    storage: DEFAULT_STORAGE,
    interactions: [
      { drug: "Loperamide (Imodium)", level: "yellow", why: "Pick one, no use both." },
      { drug: "ORS", level: "green", why: "Drink ORS plenty — e dey help." },
    ],
    warning: "If belle still dey run after 24 hours, see Pharmacist.",
    science: {
      phytochemicals: ["Mangiferin (xanthone)", "Tannins (gallotannins)", "Quercetin", "Kaempferol"],
      evidence: {
        citation: "J. Ethnopharmacology, 2018",
        summary:
          "Mangifera indica stem-bark extract (Vimang®) reduced acute diarrhoea episodes by ~52% vs placebo in a 120-patient Cuban trial — credited to tannin astringency.",
      },
      toxicity: {
        ld50: "> 2000 mg/kg (oral, rat)",
        notes:
          "Bark tannins fit irritate stomach and reduce iron absorption. No use pass 3 days.",
      },
      cypInteraction: "Mangiferin mildly inhibits CYP3A4 and P-glycoprotein.",
      source: {
        label: "PubMed: Mangifera indica clinical trial (PMID 29698773)",
        url: "https://pubmed.ncbi.nlm.nih.gov/29698773/",
      },
    },
  },
];

export function findRemediesFor(symptomKeys: string[]): Remedy[] {
  if (symptomKeys.length === 0) return [];
  return REMEDIES.filter((r) => r.treats.some((t) => symptomKeys.includes(t)));
}

export function matchSymptomsFromText(text: string): string[] {
  const t = text.toLowerCase();
  const map: Record<string, string[]> = {
    malaria: ["malaria", "body hot", "fever", "shiver", "cold body"],
    stomach: ["belle", "stomach", "tommy", "ulcer", "gas"],
    cough: ["cough", "chest"],
    cold: ["catarrh", "cold", "nose", "sneeze"],
    headache: ["head", "headache", "migraine", "bang"],
    diarrhea: ["run belle", "diarrhea", "running stomach", "purge", "shit"],
    wound: ["wound", "cut", "burn", "sore"],
    bp: ["bp", "pressure", "hypertension"],
  };
  const hits: string[] = [];
  for (const [k, words] of Object.entries(map)) {
    if (words.some((w) => t.includes(w))) hits.push(k);
  }
  return hits;
}
